### PR TITLE
0.0.42

### PR DESCRIPTION
**Pull request by Langer9876**
Preloader added to inventory check when no hunting drops and when merging.
Merging runs asynchronously (hunt again is blocked while it runs).
Checking whether to keep hunt again disabled or not runs every 250ms rather than every 1 second, until it's clear.

### CODE REVIEW

**Comment by rodmk** [comment]
Did you intend to have 3 commits? The last one seems to be reverting the changes of the second one.

**Comment by rodmk** [comment]
I cherry-picked the good commit. Thanks!
https://github.com/rodmk/legacy_enhancement_suite/commit/f11fcf9bc1014c34963e017ed3770088fc7094f5

**Comment by rodmk** [comment]
Oooh I get it now, the last commit was a fix for some things in the second.

Generally, if you can, I'd prefer one commit per pull request (feel free to just amend with fixes). I'll patch the second commit on as well.

**Comment by Langer9876** [comment]
Ah I see. The first was me merging the branch to my own master, that you accepted before (oops). The second was the commit described and the third was a minor fix to it (and I got mixed up with the version number).

I don't think I'll code on Fridays anymore, heh.

**Pull request closed without merging**
